In [1]:
import numpy as np

In [2]:
#1. Download data
path = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris_data = np.genfromtxt(path, delimiter=',', usecols=(0,1,2,3), skip_header = 0)
print(iris_data[:5, :])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [3]:
#2. Is/transform -> 2D-array
print(type(iris_data))
iris_data.ndim

<class 'numpy.ndarray'>


2

In [4]:
#3.0 My own test
np.random.seed(11)
arr_test1 = np.random.randint(0,10,(3,3))
print(arr_test1)
print(arr_test1[:, 0])
print(np.mean(arr_test1[:, 0]))
print(np.median(arr_test1[:, 0]))
print(np.std(arr_test1[:, 0]))

[[9 0 1]
 [7 1 7]
 [2 8 0]]
[9 7 2]
6.0
7.0
2.943920288775949


In [5]:
#3. mean, median, standard deviation for first column (col 0)
print('Mean column 0 = ', np.mean(iris_data[:, 0]))
print('Median column 0 = ', np.median(iris_data[:, 0]))
print('Standard deviation column 0 = ', np.std(iris_data[:, 0]))

Mean column 0 =  5.843333333333334
Median column 0 =  5.8
Standard deviation column 0 =  0.8253012917851409


In [6]:
#4.0 TEST
np.random.seed(11)
arr_test1 = np.random.random((4,4))
print(arr_test1)
arr_test1_nan = arr_test1.flatten()
arr_test_random4_indices = np.random.choice(arr_test1.size, 4 , replace=False)
arr_test1_nan[arr_test_random4_indices] = np.nan
print(arr_test_random4_indices)
print(arr_test1_nan)

[[0.18026969 0.01947524 0.46321853 0.72493393]
 [0.4202036  0.4854271  0.01278081 0.48737161]
 [0.94180665 0.85079509 0.72996447 0.10873607]
 [0.89390417 0.85715425 0.16508662 0.63233401]]
[12  4  9  7]
[0.18026969 0.01947524 0.46321853 0.72493393        nan 0.4854271
 0.01278081        nan 0.94180665        nan 0.72996447 0.10873607
        nan 0.85715425 0.16508662 0.63233401]


In [7]:
#4.Insert 20 unique random np.nan in array
ncols = iris_data.shape[1]
nrows = iris_data.shape[0]
numbers_nan = 20

iris_data_nan = iris_data.flatten()
random_indices = np.random.choice(ncols*nrows, numbers_nan, replace = False)

iris_data_nan[random_indices] = np.nan #insert 20 nan to random places
print(np.isnan(iris_data_nan).sum())
iris_data_nan = iris_data_nan.reshape((nrows, ncols)) #reshape
print(iris_data_nan[:20])

20
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 nan 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]]


In [8]:
#4.1 Insert 20 unique random np.nan in array (ver2)
ncols = iris_data.shape[1]
nrows = iris_data.shape[0]
numbers_nan = 20
iris_data_nan2 = iris_data.copy()

#iris_data_nan2 = iris_data.flatten()
random_indices = np.random.choice(iris_data.size, numbers_nan, replace = False)

iris_data_nan2.ravel()[random_indices] = np.nan #(!)insert 20 nan to random places

print(iris_data_nan[:20])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 nan 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]]


In [9]:
#TEST
np.random.seed(11)
arr_test1 = np.random.random((4,4))
arr_test1[1, 0], arr_test1[3, 0], arr_test1[2,2] = np.nan, np.nan, np.nan
print(arr_test1)
np.where(np.isnan(arr_test1[:, 0]))[0]

[[0.18026969 0.01947524 0.46321853 0.72493393]
 [       nan 0.4854271  0.01278081 0.48737161]
 [0.94180665 0.85079509        nan 0.10873607]
 [       nan 0.85715425 0.16508662 0.63233401]]


array([1, 3])

In [10]:
#5. Positions np.nan in col0
obj_col = 0
print('Positions np.nan in col',obj_col, ':',  np.where(np.isnan(iris_data_nan[:, obj_col]))[0])

Positions np.nan in col 0 : [ 20  24  59  68  80  85 111 126 134 137]


In [11]:
#6. Filter col2 >1.5 & col0 < 5.0

mask = (iris_data_nan[:, 2] > 1.5) & (iris_data_nan[:, 0] < 5.0)
iris_data_nan_filtered = iris_data[mask, :] #rows that satisfy the condition
print(iris_data_nan_filtered)

[[4.8 3.4 1.6 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [12]:
#7. np.nan -> 0
print(iris_data_nan[:20])
iris_data_nan[np.isnan(iris_data_nan)] = 0
print(iris_data_nan[:20])



[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 nan 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]]
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 0.  1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]]


In [13]:
iris_data_task = iris_data_nan #rename dataset

In [14]:
#8. All unique values with counts

uniqs, counts = np.unique(iris_data_nan, return_counts = True)
print("Unique\n items :", "Counts:")
print(np.hstack([uniqs.reshape(uniqs.shape[0], 1), counts.reshape(counts.shape[0], 1)]))
#print("Unique items : ", uniqs.reshape(uniqs.shape[0], 1))
#print("Counts       : ", counts.reshape(counts.shape[0], 1))


Unique
 items : Counts:
[[ 0.  20. ]
 [ 0.1  6. ]
 [ 0.2 26. ]
 [ 0.3  7. ]
 [ 0.4  7. ]
 [ 0.6  1. ]
 [ 1.   7. ]
 [ 1.1  4. ]
 [ 1.2  7. ]
 [ 1.3 20. ]
 [ 1.4 19. ]
 [ 1.5 26. ]
 [ 1.6 11. ]
 [ 1.7  6. ]
 [ 1.8 12. ]
 [ 1.9  7. ]
 [ 2.   7. ]
 [ 2.1  6. ]
 [ 2.2  6. ]
 [ 2.3 12. ]
 [ 2.4  5. ]
 [ 2.5 11. ]
 [ 2.6  5. ]
 [ 2.7  9. ]
 [ 2.8 14. ]
 [ 2.9 10. ]
 [ 3.  27. ]
 [ 3.1 12. ]
 [ 3.2 13. ]
 [ 3.3  7. ]
 [ 3.4 11. ]
 [ 3.5  8. ]
 [ 3.6  4. ]
 [ 3.7  4. ]
 [ 3.8  7. ]
 [ 3.9  5. ]
 [ 4.   6. ]
 [ 4.1  4. ]
 [ 4.2  5. ]
 [ 4.3  3. ]
 [ 4.4  8. ]
 [ 4.5  9. ]
 [ 4.6  7. ]
 [ 4.7  7. ]
 [ 4.8  8. ]
 [ 4.9 11. ]
 [ 5.  13. ]
 [ 5.1 17. ]
 [ 5.2  5. ]
 [ 5.3  3. ]
 [ 5.4  7. ]
 [ 5.5  9. ]
 [ 5.6 12. ]
 [ 5.7 11. ]
 [ 5.8 10. ]
 [ 5.9  5. ]
 [ 6.   7. ]
 [ 6.1  8. ]
 [ 6.2  2. ]
 [ 6.3  9. ]
 [ 6.4  6. ]
 [ 6.5  5. ]
 [ 6.6  3. ]
 [ 6.7 10. ]
 [ 6.8  3. ]
 [ 6.9  5. ]
 [ 7.   1. ]
 [ 7.1  1. ]
 [ 7.2  3. ]
 [ 7.3  1. ]
 [ 7.4  1. ]
 [ 7.6  1. ]
 [ 7.7  4. ]
 [ 7.9  1. ]]


In [15]:
# TEST (9.0)
np.random.seed(11)
arr_test1 = np.random.random((4,4))
print(arr_test1)
np.split(arr_test1, 2)

[[0.18026969 0.01947524 0.46321853 0.72493393]
 [0.4202036  0.4854271  0.01278081 0.48737161]
 [0.94180665 0.85079509 0.72996447 0.10873607]
 [0.89390417 0.85715425 0.16508662 0.63233401]]


[array([[0.18026969, 0.01947524, 0.46321853, 0.72493393],
        [0.4202036 , 0.4854271 , 0.01278081, 0.48737161]]),
 array([[0.94180665, 0.85079509, 0.72996447, 0.10873607],
        [0.89390417, 0.85715425, 0.16508662, 0.63233401]])]

In [16]:
#9. Split array into 2 eq.parts

array_splitted = np.split(iris_data_task, 2, axis=0 )
array_up, array_down = array_splitted[0], array_splitted[1]
print('Shape array_up:', array_up.shape)
print('Shape array_down:', array_down.shape)


Shape array_up: (75, 4)
Shape array_down: (75, 4)


In [17]:
#TEST (10.0)
# Get the index positions that would sort the array
np.random.seed(11)
arr_test1 = np.random.random((4,4))
print(arr_test1)
sorted_index_1stcol_arr_test1 = arr_test1[:, 0].argsort()
arr_test1[sorted_index_1stcol_arr_test1]

[[0.18026969 0.01947524 0.46321853 0.72493393]
 [0.4202036  0.4854271  0.01278081 0.48737161]
 [0.94180665 0.85079509 0.72996447 0.10873607]
 [0.89390417 0.85715425 0.16508662 0.63233401]]


array([[0.18026969, 0.01947524, 0.46321853, 0.72493393],
       [0.4202036 , 0.4854271 , 0.01278081, 0.48737161],
       [0.89390417, 0.85715425, 0.16508662, 0.63233401],
       [0.94180665, 0.85079509, 0.72996447, 0.10873607]])

In [18]:
#10 Sort
'''
Sort array_up by first column
Sort array_down by first column desc
'''

sorted_index_1stcol_arr_up = array_up[:, 0].argsort() #sort arr_up ascending order
sorted_index_1stcol_arr_down_desc = array_down[:, 0].argsort()[::-1] #sort arr_down descending order

array_up_sorted = array_up[sorted_index_1stcol_arr_up]
array_down_sorted_desc = array_down[sorted_index_1stcol_arr_down_desc]
print(array_up_sorted[:20])
print(array_down_sorted_desc[:20])

[[0.  3.4 1.9 0.2]
 [0.  2.7 3.9 1.4]
 [0.  2.2 4.5 1.5]
 [0.  3.4 1.7 0.2]
 [4.3 3.  1.1 0.1]
 [4.4 3.  1.3 0. ]
 [4.4 3.2 1.3 0. ]
 [4.4 2.9 1.4 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.6 1.  0.2]
 [4.6 3.2 1.4 0.2]
 [4.6 0.  1.4 0.3]
 [4.6 3.1 1.5 0.2]
 [4.7 3.2 1.3 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.8 3.1 1.6 0.2]
 [4.8 3.  1.4 0.3]
 [4.9 3.1 1.5 0.1]]
[[7.9 3.8 6.4 2. ]
 [7.7 2.8 6.7 2. ]
 [7.7 2.6 6.9 2.3]
 [7.7 3.8 6.7 2.2]
 [7.7 3.  6.1 2.3]
 [7.6 3.  6.6 2.1]
 [7.4 2.8 6.1 1.9]
 [7.3 2.9 0.  1.8]
 [7.2 3.  5.8 1.6]
 [7.2 3.6 6.1 2.5]
 [7.2 3.2 6.  1.8]
 [7.1 3.  5.9 2.1]
 [6.9 3.1 5.4 2.1]
 [6.9 3.1 5.1 2.3]
 [6.9 3.2 5.7 2.3]
 [6.8 3.2 5.9 2.3]
 [6.8 2.8 4.8 1.4]
 [6.8 3.  5.5 2.1]
 [6.7 3.3 5.7 2.1]
 [6.7 3.1 5.6 2.4]]


In [19]:
#11. Concatenate arrays

array_joint = np.concatenate([array_up_sorted, array_down_sorted_desc], axis = 0)

print(array_joint[:20])  #first 20 rows
print(array_joint[-20:]) #last 20 rows

[[0.  3.4 1.9 0.2]
 [0.  2.7 3.9 1.4]
 [0.  2.2 4.5 1.5]
 [0.  3.4 1.7 0.2]
 [4.3 3.  1.1 0.1]
 [4.4 3.  1.3 0. ]
 [4.4 3.2 1.3 0. ]
 [4.4 2.9 1.4 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.6 1.  0.2]
 [4.6 3.2 1.4 0.2]
 [4.6 0.  1.4 0.3]
 [4.6 3.1 1.5 0.2]
 [4.7 3.2 1.3 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.8 3.1 1.6 0.2]
 [4.8 3.  1.4 0.3]
 [4.9 3.1 1.5 0.1]]
[[5.7 2.6 3.5 1. ]
 [5.7 2.8 4.1 1.3]
 [5.7 2.9 4.2 1.3]
 [5.7 3.  4.2 1.2]
 [5.6 3.  4.1 1.3]
 [5.6 2.8 4.9 2. ]
 [5.6 2.7 4.2 1.3]
 [5.5 2.6 4.4 1.2]
 [5.5 2.5 4.  1.3]
 [5.5 2.4 3.7 1. ]
 [5.4 3.  4.5 1.5]
 [5.1 2.5 3.  1.1]
 [5.  2.3 3.3 1. ]
 [4.9 2.5 4.5 1.7]
 [0.  3.1 5.5 1.8]
 [0.  2.7 5.3 1.9]
 [0.  2.4 3.8 1.1]
 [0.  3.4 4.5 1.6]
 [0.  2.8 4.8 1.8]
 [0.  2.6 5.6 1.4]]


In [33]:
#12.0
print(array_joint[array_joint == 0.0])
print(array_joint[array_joint == 3.0])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3.]


In [47]:
#12 Find most frequent value in array (ver1)
uniq_val, uniq_value_frequency = np.unique(array_joint, return_counts=True)
print('Unique values\n', uniq_val)
print('Unique values frequences\n', uniq_value_frequency)
print('Total count  unique values frequences:', uniq_value_frequency.sum())
print('\nMost frequent value is:', uniq_val[np.argmax(uniq_value_frequency)]) # most frequent value (mode)

Unique values
 [0.  0.1 0.2 0.3 0.4 0.6 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1
 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9
 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7
 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.6
 7.7 7.9]
Unique values frequences
 [20  6 26  7  7  1  7  4  7 20 19 26 11  6 12  7  7  6  6 12  5 11  5  9
 14 10 27 12 13  7 11  8  4  4  7  5  6  4  5  3  8  9  7  7  8 11 13 17
  5  3  7  9 12 11 10  5  7  8  2  9  6  5  3 10  3  5  1  1  3  1  1  1
  4  1]
Total count  unique values frequences: 600

Most frequent value is: 3.0


In [21]:
#12 Find most frequent value in array (ver2)
import statistics as st
print('Most frequent value is:', st.mode(array_joint.flatten()))

Most frequent value is: 3.0


In [22]:
#13 Function
'''
Transform input array:
      Xi*2 if Xi<Xavg
      Xi/4 if Xi<=Xavg

Input parameter - array
'''

def transformer_arr(array, column_index):
  average_arr = np.average(array[:, column_index])
  result = np.copy(array)  #copy in order to process values once

  result[array[:, column_index] < average_arr, column_index] *= 2
  result[array[:, column_index] >= average_arr, column_index] /= 4

  return result


In [23]:
#14 Applying function to col2
print(array_joint[:20])

array_final_hw_l2 = transformer_arr(array = array_joint, column_index = 2)

print('Transformed dataset: \n',  array_final_hw_l2[:20])

[[0.  3.4 1.9 0.2]
 [0.  2.7 3.9 1.4]
 [0.  2.2 4.5 1.5]
 [0.  3.4 1.7 0.2]
 [4.3 3.  1.1 0.1]
 [4.4 3.  1.3 0. ]
 [4.4 3.2 1.3 0. ]
 [4.4 2.9 1.4 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.6 1.  0.2]
 [4.6 3.2 1.4 0.2]
 [4.6 0.  1.4 0.3]
 [4.6 3.1 1.5 0.2]
 [4.7 3.2 1.3 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.8 3.1 1.6 0.2]
 [4.8 3.  1.4 0.3]
 [4.9 3.1 1.5 0.1]]
Transformed dataset: 
 [[0.    3.4   3.8   0.2  ]
 [0.    2.7   0.975 1.4  ]
 [0.    2.2   1.125 1.5  ]
 [0.    3.4   3.4   0.2  ]
 [4.3   3.    2.2   0.1  ]
 [4.4   3.    2.6   0.   ]
 [4.4   3.2   2.6   0.   ]
 [4.4   2.9   2.8   0.2  ]
 [4.5   2.3   2.6   0.3  ]
 [4.6   3.6   2.    0.2  ]
 [4.6   3.2   2.8   0.2  ]
 [4.6   0.    2.8   0.3  ]
 [4.6   3.1   3.    0.2  ]
 [4.7   3.2   2.6   0.2  ]
 [4.7   3.2   3.2   0.2  ]
 [4.8   3.4   3.2   0.2  ]
 [4.8   3.    2.8   0.1  ]
 [4.8   3.1   3.2   0.2  ]
 [4.8   3.    2.8   0.3  ]
 [4.9   3.1   3.    0.1  ]]
